//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ui_res.rc
//
#define IDS_STR_EXPENSE                 101
#define IDB_PNG_CALC                    102
#define IDB_PNG_BEGIN                   102
#define IDS_STR_CASH                    102
#define IDB_PNG_LOGIN                   103
#define IDS_STR_CREDIT                  103
#define IDB_PNG_L_LPRESS                104
#define IDS_STR_SAVING                  104
#define IDB_PNG_L_RPRESS                105
#define IDS_STR_CONFIG_CATEGORY_EXPAND  105
#define IDB_PNG_DATE                    106
#define IDS_STR_ERR_TRANSFER_ACCOUNT    106
#define IDB_PNG_ALERT                   107
#define IDS_STR_CONFIG_AUTOLOCK         107
#define IDB_PNG_CATEGORY                108
#define IDS_STR_AUTOLOCK_IMM            108
#define IDB_PNG_ACCOUNT                 109
#define IDS_STR_SECONDS                 109
#define IDB_PNG_TOACCOUNT               110
#define IDS_STR_AUTOLOCK_TIP            110
#define IDB_PNG_ADD                     111
#define IDS_STR_FILTER                  111
#define IDB_PNG_MODIFY                  112
#define IDS_STR_CONFIG_FILTER           112
#define IDB_PNG_IMPORT                  113
#define IDS_STR_START_DATE              113
#define IDB_PNG_EXPORT                  114
#define IDS_STR_APPNAME                 114
#define IDB_PNG_LINECHART               115
#define IDS_STR_ABOUT                   115
#define IDB_PNG_PIECHART                116
#define IDS_STR_APPAUTHOR               116
#define IDB_PNG_ENCRYPT                 117
#define IDS_STR_APPVERSION              117
#define IDB_PNG_BACKUP                  118
#define IDS_STR_ADDTIONAL               118
#define IDB_PNG_RELOADALERT             119
#define IDS_STR_RETURN                  119
#define IDB_PNG_L_LRELEASE              120
#define IDS_STR_OK                      120
#define IDB_PNG_L_RRELEASE              121
#define IDS_STR_CANCEL                  121
#define IDB_PNG_S_EDIT                  122
#define IDS_STR_IMPORT                  122
#define IDB_PNG_S_DEL                   123
#define IDS_STR_EXPORT                  123
#define IDB_PNG_L_UPRESS                124
#define IDS_STR_BACKUP_DB               124
#define IDB_PNG_L_DPRESS                125
#define IDS_STR_SETUP_PWD               125
#define IDB_PNG_L_URELEASE              126
#define IDS_STR_RECOVER_ALARM           126
#define IDB_PNG_L_DRELEASE              127
#define IDS_STR_OPTDB                   127
#define IDB_PNG_EXPANED                 128
#define IDS_STR_ACCOUNT                 128
#define IDB_PNG_COLLAPSED               129
#define IDS_STR_CATEGORY                129
#define IDB_PNG_COINS                   130
#define IDS_STR_RECORDS                 130
#define IDB_PNG_OPTIMIZE                131
#define IDS_STR_IMPORT_CC               131
#define IDB_PNG_IN_BAR                  132
#define IDS_STR_IMPORT_TC               132
#define IDB_PNG_OUT_BAR                 133
#define IDS_STR_DATE_RANGE              133
#define IDB_PNG_BAL_BAR                 134
#define IDS_STR_ALLDATE                 134
#define IDB_PNG_IN_HEAD                 135
#define IDS_STR_DATE                    135
#define IDB_PNG_OUT_HEAD                136
#define IDS_STR_ALARM                   136
#define IDB_PNG_BAL_HEAD_IN             137
#define IDS_STR_DISABLED                137
#define IDB_PNG_BAL_HEAD_OUT            138
#define IDB_PNG_PERSON					139
#define IDB_PNG_END                     139
#define IDS_STR_ENABLED                 138
#define IDS_STR_CYCLE                   139
#define IDS_STR_YYYYMMDD                140
#define IDS_STR_EVERY_DAY               141
#define IDS_STR_EVERY_MONTH             142
#define IDS_STR_EVERY_YEAR              143
#define IDS_STR_ALL_CATEGORY            144
#define IDS_STR_ALL_ACCOUNT             145
#define IDS_STR_MORE                    146
#define IDS_STR_MONTHLY_EXREPORT        147
#define IDS_STR_MONTHLY_INREPORT        148
#define IDS_STR_YEARLY_REPORT           149
#define IDS_STR_BROWSE_MODE             150
#define IDS_STR_ORDER_MODE              151
#define IDS_STR_DETAIL                  152
#define IDS_STR_SIMPLE                  153
#define IDS_STR_BYTIME                  154
#define IDS_STR_BYACCOUNT               155
#define IDS_STR_BYCATEGORY              156
#define IDS_STR_ERRAMOUNT               157
#define IDS_STR_DELETE                  158
#define IDS_STR_BACKUP                  159
#define IDS_STR_CONFIRM                 160
#define IDS_STR_EXPORT_CC               161
#define IDS_STR_EXPORT_TC               162
#define IDS_STR_EXPORT_CHOOSE_ALL       163
#define IDS_STR_SUCCEED                 164
#define IDS_STR_FAILED                  165
#define IDS_STR_EXPORT_QIF              166
#define IDS_STR_PASSWORD                167
#define IDS_STR_NEW_PWD                 168
#define IDS_STR_PWD_TIP                 169
#define IDS_STR_PWD_CLEAR_S             170
#define IDS_STR_PWD_SET_S               171
#define IDS_STR_PWD_INCORRECT           172
#define IDS_STR_YYYYMM                  173
#define IDS_STR_NO_DATA                 174
#define IDS_STR_MM                      175
#define IDS_STR_EDIT                    176
#define IDS_STR_NEW                     177
#define IDS_STR_SELECT                  178
#define IDS_STR_ACCOUNT_LIST            179
#define IDS_STR_CATEGORY_LIST           180
#define IDS_STR_TRANS_LIST              181
#define IDS_STR_BALANCE1                182
#define IDS_STR_TRANS_DETAIL            183
#define IDS_STR_NOTE                    184
#define IDS_STR_EXIT                    185
#define IDS_STR_CONFIG                  186
#define IDS_STR_BROWSE                  187
#define IDS_STR_TO_ACCOUNT              188
#define IDS_STR_WEEKDAY_NAME0           189
#define IDS_STR_WEEKDAY_NAME1           190
#define IDS_STR_WEEKDAY_NAME2           191
#define IDS_STR_WEEKDAY_NAME3           192
#define IDS_STR_WEEKDAY_NAME4           193
#define IDS_STR_WEEKDAY_NAME5           194
#define IDS_STR_WEEKDAY_NAME6           195
#define IDS_STR_NO_TRANSACTION          196
#define IDS_STR_EDIT_ACCOUNT            197
#define IDS_STR_INIT_AMOUNT             198
#define IDS_STR_UPDATE                  199
#define IDS_STR_NEW_ACCOUNT             200
#define IDS_STR_NAME                    201
#define IDS_STR_AMOUNT_UNIT             202
#define IDS_STR_SAVE                    203
#define IDS_STR_WARN_ACCOUNT_NAME       204
#define IDS_STR_ERR_ACCOUNT_ADDDUP      205
#define IDS_STR_ERR_ACCOUNT_UPDATEDUP   206
#define IDS_STR_INFO_ACCOUNT_ADDS       207
#define IDS_STR_INFO_ACCOUNT_UPDATES    208
#define IDS_STR_ERR_ACCOUNT_INUSE       209
#define IDS_STR_WARN_ACCOUNT_DELETE     210
#define IDS_STR_ERR_TRANS_AMOUNT        211
#define IDS_STR_ERR_TRANS_MINUS         212
#define IDS_STR_CONFIRM_EXIT            213
#define IDS_STR_TRANS_ADD               214
#define IDS_STR_TRANS_UPDATE            215
#define IDS_STR_HOUR                    216
#define IDS_STR_MIN                     217
#define IDS_STR_EVERY_WEEK              218
#define IDS_STR_AMOUNT                  219
#define IDS_STR_INPUT_TIP               220
#define IDS_STR_INPUT_TIP_MINUS         221
#define IDS_STR_DETAIL_INFO             222
#define IDS_STR_EX_ACCOUNT_FILENAME     223
#define IDS_STR_EX_CATEGORY_FILENAME    224
#define IDS_STR_EX_TRANS_ALL_FILENAME   225
#define IDS_STR_EX_TRANS_D1_FILENAME    226
#define IDS_STR_EX_TRANS_D2_FILENAME    227
#define IDS_STR_EX_UNK_FILENAME         228
#define IDS_STR_Q_BACKUP_IMPORT         229
#define IDS_STR_ERR_IMPORT_FORMAT       230
#define IDS_STR_ERR_IMPORT_UNK_FORMAT   231
#define IDS_STR_IMPORT_WAIT             232
#define IDS_STR_IMPORT_ANALYSIS         233
#define IDS_STR_IMPORT_RECORD           234
#define IDS_STR_IMPORT_RESULT           235
#define IDS_STR_TRANSFER                236
#define IDS_STR_INCOME                  237
#define IDS_STR_EXPORT_RESULT           238
#define IDS_STR_EXPORT_WAIT             239
#define IDS_STR_ACCOUNT_TITLE_FORMAT_S  240
#define IDS_STR_CATEGORY_TITLE_FORMAT_S 241
#define IDS_STR_RECORD_TITLE_FORMAT_S   242
#define IDS_STR_ACCOUNT_TITLE_FORMAT_C  243
#define IDS_STR_CATEGORY_TITLE_FORMAT_C 244
#define IDS_STR_RECORD_TITLE_FORMAT_C   245
#define IDS_STR_ACCOUNT_TITLE_FORMAT_EXCEL_C 246
#define IDS_STR_CATEGORY_TITLE_FORMAT_EXCEL_C 247
#define IDS_STR_RECORD_TITLE_FORMAT_EXCEL_C 248
#define IDS_STR_OPERATE                 249
#define IDS_STR_BACKUP_S                250
#define IDS_STR_DELETE_S                251
#define IDS_STR_WARN_RESET              252
#define IDS_STR_WARN_RESTORE            253
#define IDS_STR_RESTORE                 254
#define IDS_STR_BACKUP_RESTORE          255
#define IDS_STR_CONFIRM_DELETE          256
#define IDS_STR_DB_OPT_S                257
#define IDS_STR_ALARM_RESTORE_S         258
#define IDS_STR_WARN_ALARM_RESTORE      259
#define IDS_STR_SUM_INEX                260
#define IDS_STR_SUM_INOUT               261
#define IDS_STR_SWITCH                  262
#define IDS_STR_30DAY                   263
#define IDS_STR_IN                      264
#define IDS_STR_OUT                     265
#define IDS_STR_BALANCE                 266
#define IDS_STR_YEARLY_TITLE            267
#define IDS_STR_MONTHLY_TITLE           268
#define IDS_STR_PREV_YEAR               269
#define IDS_STR_NEXT_YEAR               270
#define IDS_STR_THIS_YEAR               271
#define IDS_STR_DAILY_TIP               272
#define IDS_STR_NEW_CATEGORY            273
#define IDS_STR_EDIT_CATEGORY           274
#define IDS_STR_PARENT_CATEGORY         275
#define IDS_STR_WARN_CATEGORY_SETNAME   276
#define IDS_STR_ERR_CATEGORY_UPDATE     277
#define IDS_STR_INFO_CATEGORY_UPDATES   278
#define IDS_STR_WARN_CATEGORY_DELETE    279
#define IDS_STR_ERR_CATEGORY_INUSE      280
#define IDS_STR_ERR_CATEGORY_ADD        281
#define IDS_STR_INFO_CATEGORY_ADDS      282
#define IDS_STR_END_DATE                283
#define IDS_STR_PERSON_DEFAULT          284
#define IDS_STR_PERSON_TITLE            285
#define IDS_STR_PERSON_FAMILY           286
#define IDS_STR_PERSON_CONTACT          287
#define IDS_STR_PERSON_INSTITUTION      288
#define IDS_STR_NEW_PERSON              289
#define IDS_STR_EDIT_PERSON             290
#define IDS_STR_PERSON_TYPE             291
#define IDS_STR_WARN_PERSON_DELETE      292
#define IDS_STR_ERR_PERSON_INUSE        293
#define IDS_STR_WARN_PERSON_SETNAME     294
#define IDS_STR_ERR_PERSON_UPDATE       295
#define IDS_STR_INFO_PERSON_UPDATES     296
#define IDS_STR_ERR_PERSON_ADD          297
#define IDS_STR_INFO_PERSON_ADDS        298
#define IDS_STR_PERSON_ALL              299

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
